# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Aseo'), ('H', 'Herramientas'), ('O', 'Oficina')], max_length=1, null=True)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=40, verbose_name='Codigo')),
                ('marca', models.CharField(max_length=40, verbose_name='Marca')),
                ('serie', models.CharField(max_length=40, verbose_name='Serie')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
