# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_auto_20170830_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='categoria',
            field=models.CharField(choices=[('A', 'Aseo'), ('H', 'Herramientas'), ('O', 'Oficina')], max_length=1, null=True),
        ),
    ]
